### ISSUE TITLE
Clients5.google.com is potentially dangerous

### ISSUE THREAD

**Issue by Accipiter7** [DavideGalilei/gpytranslate#2]
https://www.google.com/amp/s/howtoremove.guide/clients5-google-com-malware/amp/

**Comment by alsoGAMER** [comment]
Sorry man, what actually your problem is?
How do you can possibly think that A GOOGLE'S SUBDOMAIN is malware?

And also, to be honest, if you inform yourself using such sites, I don't know how to help you.
With that said, stop opening random issues or I'll ban you.
