### ISSUE TITLE
[Bug]: TypeError: Response.iter_bytes() got an unexpected keyword argument 'chunk_size'

### ISSUE THREAD

**Issue by NikitaBeloglazov** [DavideGalilei/gpytranslate#25]
### What happened?

TTS doesn't work at all.
I use the example from the documentation https://pypi.org/project/gpytranslate/

```python3
from gpytranslate import SyncTranslator
translator = SyncTranslator()

with open("test.mp3", "wb") as file:
    translator.tts("Hello world!", file=file)
```

### OS / Environment

OpenSUSE Tumbleweed x86_64, Python 3.10.10, gpytranslate 1.5.1 (from pip)

### Traceback

```python-traceback
>>> with open("test.mp3", "wb") as file:
...     translator.tts("hello", file=file)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/nikita/.local/lib/python3.10/site-packages/gpytranslate/sync/sync_translator.py", line 197, in tts
    raise TranslationError(e) from None
gpytranslate.exceptions.TranslationError: An error occurred while trying to translate/tts: TypeError("Response.iter_bytes() got an unexpected keyword argument 'chunk_size'")
```

### Searched before submitting

- [X] I searched for duplicates, and didn't found anything.
- [X] I searched this bug on a search engine, and didn't found anything.

**Comment by DavideGalilei** [comment]
This error is related to `httpx` (the underlying requests library used by gpytranslate). Have you tried reinstalling httpx to a more recent version?
I tested on my local machine but couldn't reproduce this issue.

**Comment by NikitaBeloglazov** [comment]
`googletrans 4.0.0rc1 requires httpx==0.13.3`.
I deleted it, updated httpx to 0.24.0, аnd TTS worked, thanks!

Thanks for such a nice module! _(googletrans shit lol)_
