### ISSUE TITLE
Library cannot be used in Python 3.6 and 3.7

### ISSUE THREAD

**Issue by alissonlauffer** [DavideGalilei/gpytranslate#5]
Although it requires `>=3.6` in `setup.py`, it is not usable in versions 3.6 and 3.7 since it is using some features implemented in 3.8+, such as `typing.Literal`.

And for the testing workflow, why not using a Python version matrix to check if it is working on all Python versions?

**Comment by DavideGalilei** [comment]
Fixed on #6
